name: Deploy

on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: AWS Test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          pip3 install awscli
          aws s3 ls
      - name: Install pipenv
        run: pip3 install pipenv
      - name: Install dependecies (including dev)
        run: pipenv sync --dev
      - name: Run tests
        run: pipenv run pytest


