name: Deploy

on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
   steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install pipenv
        run: pip3 install pipenv

      - uses: actions/checkout@v2 # Checking out the repo

      - name: Install dependecies (including dev)
        run: pipenv sync --dev

      - name: Run tests
        run: pipenv run pytest