name: Deploy

on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        - with:
            python-version: "3.8"

      - name: Install pipenv
        run: pip3 install pipenv

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependecies (including dev)
        run: pipenv sync --dev

      - name: Run tests
        run: pipenv run pytest