name: Deploy

on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Python 3.8 and pipenv
        run: |
          sudo apt-get update -y
          sudo apt-get install python3.8 python3-pip -y
          pip3 install --user pipenv

      - uses: actions/checkout@v2 # Checking out the repo

      - name: Install dependecies (including dev)
        run: pipenv sync --dev

      - name: Run tests
        run: pipenv run pytest